// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biczeacrpjnrbaitujsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpY3plYWNycGpucmJhaXR1anNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzkyMzEsImV4cCI6MjA2NTQ1NTIzMX0.WaknWSAauBfK_8W9RY1fwPOcIeyh03hIy9QhvWev2M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);